version: "3"

services:
  auth:
    image: node:lts-alpine
    working_dir: /usr/src/app
    volumes:
      - ./auth/package.json:/usr/src/app/package.json
      - ./auth/tsconfig.json:/usr/src/app/tsconfig.json
      - ./auth/src:/usr/src/app/src
      - ./auth/node_modules:/usr/src/app/node_modules
    env_file: env/.docker-compose.env
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    env_file: env/.docker-compose.env
    ports:
      - "54320:5432"
    volumes:
      - server_db:/var/lib/postgresql/data
volumes:
  server_db:
