version: "3"

services:
  gateway:
    container_name: gateway
    image: node:lts-alpine
    working_dir: /usr/src/app
    volumes:
      - ./gateway/package.json:/usr/src/app/package.json
      - ./gateway/tsconfig.json:/usr/src/app/tsconfig.json
      - ./gateway/src:/usr/src/app/src
      - ./gateway/node_modules:/usr/src/app/node_modules
    env_file: env/.docker-compose.env
    command: node_modules/.bin/ts-node-dev src/main --colors --transpileOnly --debounce 1500
    ports:
      - 3000:3000
    depends_on:
      - authentication

  authentication:
    container_name: authentication
    image: node:lts-alpine
    working_dir: /usr/src/app
    volumes:
      - ./authentication/package.json:/usr/src/app/package.json
      - ./authentication/tsconfig.json:/usr/src/app/tsconfig.json
      - ./authentication/src:/usr/src/app/src
      - ./authentication/node_modules:/usr/src/app/node_modules
    env_file: env/.docker-compose.env
    command: node_modules/.bin/ts-node-dev src/main --colors --transpileOnly --debounce 1500
